const intereses: string[] = [
    // Deportes
    "Fútbol",
    "Baloncesto",
    "Béisbol",
    "Fútbol Americano",
    "Tenis",
    "Golf",
    "Críquet",
    "Rugby",
    "Hockey",
    "Boxeo",
    "Artes Marciales",
    "Correr",
    "Ciclismo",
    "Natación",
    "Skateboarding",
    "Surf",
  
    // Aire libre y aventura
    "Senderismo",
    "Camping",
    "Pesca",
    "Caza",
    "Viajes por carretera",
    "Viajar",
    "Viajes de aventura",
    "Naturaleza",
    "Vida salvaje",
    "Navegación",
    "Buceo",
    "Aistamiento de aves",
    "Observación de estrellas",
  
    // Música y vida nocturna
    "Música",
    "Reggaetón",
    "Salsa",
    "Merengue",
    "Vallenato",
    "Rock",
    "Pop",
    "Hip-Hop",
    "Rap",
    "Jazz",
    "Clásica",
    "Country",
    "Electrónica",
    "R&B",
    "Metal",
    "Punk",
    "Indie",
    "Blues",
    "Reggae",
    "Folk",
    "Alternativa",
    "Vida nocturna",
    "Bailar",
    "Bares",
    "Fiestas",
    "Socializar",
    "Fraternidades",
  
    // Arte, cultura y entretenimiento
    "Fotografía",
    "Pintura",
    "Dibujo",
    "Escultura",
    "Diseño",
    "Arquitectura",
    "Teatro",
    "Cine",
    "Películas",
    "Televisión",
    "Anime",
    "Caricaturas",
    "Literatura",
    "Libros",
    "Escritura",
    "Poesía",
    "Cómics",
    "Museos",
    "Arte",
    "Moda",
    "Estilo",
    "Belleza",
    "Tatuajes",
    "Piercings",
    "Stand-up Comedy",
    "Improvisación",
    "Conciertos",
    "Ópera",
    "Ballet",
    "Canto",
    "DJ",
  
    // Juegos y tecnología
    "Videojuegos",
    "Juegos de mesa",
    "Juegos de rol",
    "Tecnología",
    "Programación",
    "Codificación",
    "Robótica",
    "Manualidades",
    "Computadoras",
    "Blockchain",
  
    // Comida y bebida
    "Cocina",
    "Repostería",
    "Gastronomía",
    "Restaurantes",
    "Vino",
    "Cerveza",
    "Cócteles",
    "Café",
    "Té",
    "Comida gourmet",
    "Comida orgánica",
    "Cocinar en grupo",
    "Cocina internacional",
  
    // Estilo de vida e intelectual
    "Historia",
    "Filosofía",
    "Política",
    "Ciencia",
    "Matemáticas",
    "Meditación",
    "Yoga",
    "Fitness",
    "Gimnasio",
    "Espiritualidad",
    "Religión",
    "Causas sociales",
    "Voluntariado",
    "Caridad",
  
    // Vida universitaria
    "Torneos universitarios",
    "Investigación académica",
    "Tutorías",
    "Estudiar en grupo",
    "Vida en la residencia",
    "Estudiantes de intercambio",
    "Proyectos estudiantiles",
    "Asociaciones estudiantiles",
    "Voluntariado universitario",
    "Conferencias y seminarios",
    "Hackathons",
    "Ferias de empleo",
    "Competencias académicas",
  
    // Animales y naturaleza
    "Animales",
    "Mascotas",
    "Perros",
    "Gatos",
    "Ecología",
    "Astronomía",
  
    // Negocios y cultura moderna
    "Inversiones",
    "Emprendimiento",
    "Startups",
    "Negocios",
    "Networking",
    "Podcasts",
    "Blogging",
    "Redes sociales",
    "Memes",
    "Cultura de internet",
    "Blog de viajes",
    "Vlogging",
  
    // Automóviles y más
    "Motocicletas",
    "Autos"
  ];
  
  export default intereses;